PK_MAP = {
    "studies": ["study_key"],
    "secondary_ids": ["secondary_id_key"],
    "nct_aliases": ["id_alias_key"],
    "sponsors": ["sponsor_key"],
    "collaborators": ["collaborator_key"],
    "conditions": ["condition_key"],
    "keywords": ["keyword_key"],
    "arm_groups": ["arm_group_key"],
    "interventions": ["intervention_key"],
    "intervention_aliases": ["intervention_key"],
    "primary_outcomes": ["outcome_key"],
    "secondary_outcomes": ["outcome_key"],
    "other_outcomes": ["outcome_key"],
    "central_contacts": ["contact_key"],
    "locations": ["location_key"],
    "location_contacts": ["contact_key"],
    "study_references": ["ref_key"],
    "link_references": ["link_key"],
    "ipd_references": ["ipd_key"],
    "outcome_measures": ["outcome_measure_key"],
    "outcome_measure_groups": ["group_key"],
    "outcome_measure_denom_units": ["denom_unit_key"],
    "outcome_measure_denom_counts": ["denom_count_key"],
    "outcome_measure_analyses": ["analysis_key"],
    "flow_groups": ["group_key"],
    "flow_periods": ["period_key"],
    "flow_period_milestones": ["milestone_key"],
    "withdrawal_types": ["withdrawal_type_key"],
    "flow_period_withdrawal_reasons": ["reason_key"],
    "adverse_events": ["adverse_event_key"],
    "event_groups": ["event_group_key"],
    "serious_events": ["serious_event_key"],
    "serious_event_stats": ["event_stat_key"],
    "other_events": ["other_event_key"],
    "other_event_stats": ["event_stat_key"],
    "violations": ["violation_key"],
    "conditions_mesh": ["mesh_key"],
    "conditions_mesh_ancestors": ["ancestor_key"],
    "conditions_browse_leaves": ["leaf_key"],
    "conditions_browse_branches": ["branch_key"],
    "interventions_mesh": ["mesh_key"],
    "interventions_mesh_ancestors": ["ancestor_key"],
    "interventions_browse_leaves": ["leaf_key"],
    "interventions_browse_branches": ["branch_key"],
    # bridge tables
    "study_sponsors": ["study_key", "sponsor_key"],
    "study_collaborators": ["study_key", "collaborator_key"],
    "study_conditions": ["study_key", "condition_key"],
    "study_keywords": ["study_key", "keyword_key"],
    "arm_interventions": ["study_key", "arm_group_key", "arm_intervention_key"],
    "study_interventions": ["study_key", "intervention_key"],
    "study_intervention_aliases": ["study_key", "intervention_key"],
    "study_central_contacts": ["study_key", "contact_key"],
    "study_locations": ["study_key", "location_key"],
    "study_location_contacts": ["study_key", "location_key", "contact_key"],
    "outcome_measure_groups_result": ["group_key", "outcome_measure_key", "study_key"],
    "outcome_measure_comparison_groups": [
        "study_key",
        "outcome_measure_key",
        "analysis_key",
        "group_key",
    ],
    "flow_period_milestone_achievements": [
        "study_key",
        "period_key",
        "milestone_key",
        "group_key",
    ],
    "flow_period_withdrawals": ["study_key", "period_key", "withdrawal_type_key"],
    "study_conditions_mesh": ["mesh_key", "study_key"],
    "study_conditions_mesh_ancestors": ["ancestor_key", "study_key"],
    "study_conditions_browse_leaves": ["leaf_key", "study_key"],
    "study_conditions_browse_branches": ["branch_key", "study_key"],
    "study_interventions_mesh": ["mesh_key", "study_key"],
    "study_interventions_mesh_ancestors": ["ancestor_key", "study_key"],
    "study_interventions_browse_leaves": ["leaf_key", "study_key"],
    "study_interventions_browse_branches": ["branch_key", "study_key"],
}
